### ISSUE TITLE
NPM Update

### ISSUE THREAD

**Issue by brundonsmith** [clark-stevenson/cannon.d.ts#10]
Could you please push the latest to NPM? It appears to be missing some things, and the git repository surprisingly isn't itself a valid NPM module.

**Comment by clark-stevenson** [comment]
Unfortunately this project needs archived so that is my bad.

It would seem that this project was pushed to DT some time ago:

https://www.npmjs.com/package/@types/cannon/v/0.1.2?activeTab=readme

Would you be able to try installing `npm install @types/cannon`  and try that declaration instead of this one?  It seems to be in use by a decent amount of people so I guess is reasonably fine.  

I will label this archived as soon as I can.

**Comment by clark-stevenson** [comment]
Closed for Archive
