### ISSUE TITLE
Question: Why is the "material" property on a IBodyOptions of type "number"?

### ISSUE THREAD

**Issue by nicky-lenaers** [clark-stevenson/cannon.d.ts#6]
Hi,

First of all thanks for the definition files, they help a lot.

I'm trying to create a `CANNON.Body` with `shape` and `material` properties set. However, I noticed that `material` is typed as a `number` (see [here](https://github.com/clark-stevenson/cannon.d.ts/blob/master/cannon.d.ts#L547)). In all examples I can find it references a `CANNON.Material` instance (see [here](https://github.com/schteppe/cannon.js/blob/master/demos/bounce.html) for example).

Also, the [CANNON.js Docs](http://schteppe.github.io/cannon.js/docs/classes/Body.html) refer to a `CANNON.Material` instance on the `CANNON.Body` options.

Is this correct or am I missing something?

**Comment by nicky-lenaers** [comment]
@clark-stevenson Care to comment?

**Comment by clark-stevenson** [comment]
Sorry Nicky my man, I made the change on Friday but forgot to commit. 

Keep in mind that the accuracy of these definitions may be somewhat outdated.  I wrote them a good year ago, but the project was abandoned before I could use them.  I would welcome any other changes as PR's if you find them.   Otherwise let me know any other issues. 

Thanks!

**Comment by nicky-lenaers** [comment]
@clark-stevenson Thanks a lot, didn't mean to put pressure on it! I will keep an eye out for any API changes and contribute here =). The CANNON.js repo is still in development, right?
